---
- name: Install and Start Apache2
  hosts: web_servers
  become: yes

  tasks:
  - name: Install Apache2
    apt: name=apache2 state=latest
  
  - name: Start Apache2
    service: name=apache2 state=started enabled=yes
