---
- name: Install Apache and Upload my Home Page
  hosts: web_servers
  become: yes

  vars:
    source_file: /home/ivankurop/ansible/MyWebSite/index.html
    dest_file: /var/www/html/index.html

  tasks:
  - name: Check and print  Linux Version
    debug: var=ansible_os_family

  - block:     #========Block for RedHat========

    - name: Install HTTPD
      yum: name=httpd state=latest

    - name: Start HTTPD
      service: name=httpd state=started enabled=yes

    - name: Copy MyWebPage to a Web server and launch that
      copy: src={{source_file}} dest={{dest_file}} mode=0555
      notify: Restart HTTPD RedHat

    when: ansible_os_family == "RedHat"

  - block:     #========Block for Debian========

    - name: Install Apache2
      apt: name=apache2 state=latest

    - name: Start Apache2
      service: name=apache2 state=started enabled=yes

    - name: Copy MyWebPage to a Web server and launch that
      copy: src={{source_file}} dest={{dest_file}} mode=0555
      notify: Restart Apache Debian

    when: ansible_os_family == "Debian"


  handlers:
  - name: Restart Apache Debian
    service: name=apache2 state=restarted
  - name: Restart HTTPD RedHat
    service: name=httpd state=restarted
