---
- name: Install Apache and Upload my Home Page
  hosts: web_servers
  become: yes

  vars:
    source_folder: /home/ivankurop/ansible/MyWebSite
    dest_folder: /var/www/html/

  tasks:
  - name: Check and print  Linux Version
    debug: var=ansible_os_family

  - block:     #========Block for RedHat========

    - name: Install HTTPD
      yum: name=httpd state=latest

    - name: Start HTTPD
      service: name=httpd state=started enabled=yes

    when: ansible_os_family == "RedHat"

  - block:     #========Block for Debian========

    - name: Install Apache2
      apt: name=apache2 state=latest

    - name: Start Apache2
      service: name=apache2 state=started enabled=yes

    when: ansible_os_family == "Debian"

  - name: Use Template
    template: src={{ source_folder }}/index.j2 dest={{ dest_folder }}/index.html mode=0555
    notify:
      - Restart Apache Debian
      - Restart HTTPD RedHat

  - name: Copy MyWebPage to a Web server and launch that
    copy: src={{ source_folder }}/{{ item }} dest={{ dest_folder }} mode=0555
    loop:
      - "bahams.png"
      - "bolgaria.png"
    notify:
      - Restart Apache Debian
      - Restart HTTPD RedHat

  handlers:
  - name: Restart Apache Debian
    service: name=apache2 state=restarted
    when: ansible_os_family == "Debian"

  - name: Restart HTTPD RedHat
    service: name=httpd state=restarted
    when: ansible_os_family == "RedHat"
