---
- name: Playbook of the Lesson 11
  hosts: all
  become: yes
  
  vars:
    message1: Privet
    message2: World
    secret: 7895123qweszxc

  tasks:
  
  - name: Print secret variable
    debug:
      var: secret

  - debug:
      msg: "Sekretnoe slovo = {{ secret }}"

  - debug:
      msg: "Vladelec etogo Servers -->{{ owner }}<--"
  
  - set_fact: full_message="{{ message1 }} {{ message2 }} from {{ owner }}"
  
  - debug:
      var: full_message
  
  - debug:
      var: ansible_distribution
  
  - shell: uptime
    register: results

  - debug:
      var: results.stdout
