---
- name: Install and Start Apache2
  hosts: web_servers
  become: yes

  vars:
   source_file: /home/ivankurop/ansible/MyWebSite/index.html
   dest_file: /var/www/html/index.html

  tasks:
  - name: Install Apache2
    apt: name=apache2 state=latest
  
  - name: Start Apache2
    service: name=apache2 state=started enabled=yes

  - name: Copy MyWebPage to a Web server and launch that
    copy: src={{source_file}} dest={{dest_file}} mode=0555
    notify: Restart Apache2

  handlers:
  - name: Restart Apache2
    service: name=apache2 state=restarted
