---
- name: Lesson19-01
  hosts: db_servers
  become: yes

  tasks:
  - name: PING TEST
    ping:

  - name: Task Number 1
    apt: name=treee state=latest

  - name: Task Number 2
    shell: echo HelloWorld!!!

  - name: Task Number3
    shell: echo Privet Mir!!!!!!!
